window.SUPABASE_URL = 'https://inorxdoginyirqlptbgo.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlub3J4ZG9naW55aXJxbHB0YmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE0NjMwNDksImV4cCI6MjA5NzAzOTA0OX0.a_zedSMJXFmmVsituRU-x4BBuEqByY2N5hLirvApnK0';
